### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelisp#1]
In order to launch we should have:

- [x] Emacs Lisp as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-emacs-lisp.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] add track implementors and other designated nitpickers as mentors to the track
- [x] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by canweriotnow** [comment]
> add track implementors and other designated nitpickers as mentors to the track

I remember some discussion about designated "mentors" before - is this an implemented thing now?

**Comment by kytrinyx** [comment]
Not exactly, but I can manually give people full access to all the problems in a track, even if they've not done the problems themselves.

**Comment by canweriotnow** [comment]
Ah, gotcha. Neat. Maybe down the roadmap, a system for nominating/identifying possible mentors through the app would be cool.

**Comment by kytrinyx** [comment]
Yeah, that would be incredibly helpful.

**Comment by canweriotnow** [comment]
@kytrinyx You can add me as a mentor, and maybe we can see if other @exercism/lisp folks would be interested... I toggled 'active', what needs to happen for exercism to pick that up? I forgot what happened last time we launched one. Is it manual, cron job, other?

**Comment by canweriotnow** [comment]
Oh, speaking of config.json, what is the "test_pattern" key? I haven't seen that before.

**Comment by verdammelt** [comment]
RE: "test pattern" - I don't see it in the config.json of the few projects I just checked (lisp, csharp, ruby) - so maybe it is optional and only for some corner case?

**Comment by yurrriq** [comment]
I've been curious about "test_pattern" too.. Also down to be a mentor!

**Comment by kytrinyx** [comment]
test_pattern is optional, I added it because perl tests don't have /test/ in the name. So it's a regex of how to detect whether or not a file is the test file.

**Comment by yurrriq** [comment]
:+1:

**Comment by kytrinyx** [comment]
> I forgot what happened last time we launched one. Is it manual, cron job, other?

It's manual--I run a script more or less daily to update submodules and deploy the x-api.

**Comment by canweriotnow** [comment]
I think we've hit all the targets, going to close this, feel free to re-open if I missed something
